name: pipeline
on:
  push:
    branches:
      - master
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: dev_build
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          docker-compose -f tasks/ci/docker-compose.yml build build
          docker-compose -f tasks/ci/docker-compose.yml run build
          docker-compose -f tasks/ci/docker-compose.yml down
      - name: dev_deploy
        env:
          Environment: dev
          AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          docker-compose -f tasks/ci/docker-compose.yml build deploy
          docker-compose -f tasks/ci/docker-compose.yml run deploy
          docker-compose -f tasks/ci/docker-compose.yml down
      - name: dev_integration
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          docker-compose -f tasks/ci/docker-compose.yml build integration
          docker-compose -f tasks/ci/docker-compose.yml run integration
          docker-compose -f tasks/ci/docker-compose.yml down
      - name: prod_build
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          docker-compose -f tasks/ci/docker-compose.yml build build
          docker-compose -f tasks/ci/docker-compose.yml run build
          docker-compose -f tasks/ci/docker-compose.yml down
      - name: prod_deploy
        env:
          Environment: prod
          AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          docker-compose -f tasks/ci/docker-compose.yml build deploy
          docker-compose -f tasks/ci/docker-compose.yml run deploy
          docker-compose -f tasks/ci/docker-compose.yml down
      - name: prod_integration
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          docker-compose -f tasks/ci/docker-compose.yml build integration
          docker-compose -f tasks/ci/docker-compose.yml run integration
          docker-compose -f tasks/ci/docker-compose.yml down
