name: pipeline
on:
  push:
    branches:
      - master
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          docker-compose -f tasks/ci/docker-compose.yml build build
          docker-compose -f tasks/ci/docker-compose.yml run build
          docker-compose -f tasks/ci/docker-compose.yml down
      - name: deploy_staging
        env:
          Environment: Staging
          AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          docker-compose -f tasks/ci/docker-compose.yml build deploy
          docker-compose -f tasks/ci/docker-compose.yml run deploy
          docker-compose -f tasks/ci/docker-compose.yml down
